### ISSUE TITLE
Domserve should accept the password that the judgehost tries to connect with

### ISSUE THREAD

**Issue by Riscky** [svsticky/stupidjury#5]
This is now done by hand

**Comment by maartenberg** [comment]
Approach:

- Generate a password and put it in Ansible Vault (creating it)
- Hash the password: `php -r 'print password_hash(`"{{ password }}\", PASSWORD_DEFAULT);'`, capture stdout
- Run this SQL:
  ```sql
  INSERT INTO user (username, name, password) VALUES ('judgehost', 'User for Judgehosts', '{{ pw_hash }}');
  INSERT INTO userrole (userid, userrole) VALUES (last_insert_id(), (SELECT roleid FROM role WHERE role = 'judgehost'));
  ```

  Ignore failures as this means the user already exists

**Comment by Riscky** [comment]
note the
```
/opt/domjudge/domserver/etc/initial_admin_password.secret
/opt/domjudge/domserver/etc/restapi.secret
```
files in the domserver container
